{
    "import_path": "resnet50/pytorch-cpu",
    "backend-params": {
        "model_path": "/root/mlperf_data/resnet50/model/resnet50.pth",
        "ipex": "True",
        "dnnl": "True",
        "jit": "True",
        "configure_dir": "resnet50/pytorch-cpu/resnet50_configure_jit_intel.json"
    },

    "dataset-params": {
        "data_path": "/root/mlperf_data/resnet50/dataset/ILSVRC2012_img_val/",
        "image_list": "/root/mlperf_data/resnet50/dataset/ILSVRC2012_img_val/val_map.txt",
        "total_sample_count": 50000 
    },
    
    "enqueue-params": {
        "batch_size": 1
    }
}
