{
    "import_path": "/home/sdp/sgattupa/server/frameworks.ai.benchmarking.mlperf.develop.inference-datacenter/closed/Intel/code/resnet50/pytorch-cpu/",
    "backend-params": {
        "model_path": "/home/sdp/syazdani/resnet50-19c8e357.pth",
        "ipex": "True",
        "dnnl": "True",
        "jit": "True",
        "configure_dir": "/home/sdp/sgattupa/frameworks.ai.benchmarking.mlperf.develop.inference-datacenter/closed/Intel/code/resnet50/pytorch-cpu/resnet50_configure_jit_intel.json"
    },

    "dataset-params": {
        "data_path": "/home/sdp/syazdani/dataset-imagenet-ilsvrc2012-val/",
        "image_list": "/home/sdp/syazdani/dataset-imagenet-ilsvrc2012-val/val_map.txt",
        "total_sample_count": 1024
    },
    
    "enqueue-params": {
        "batch_size": 128
    }

}
