{
    "import_path": "resnet50/pytorch-cpu",
    "backend-params": {
        "model_path": "/home/sdp/syazdani/resnet50-19c8e357.pth",
        "ipex": "True",
        "dnnl": "True",
        "jit": "True",
        "configure_dir": "resnet50/pytorch-cpu/calibration/resnet50_configure_jit_latest.json"
    },

    "dataset-params": {
        "data_path": "/home/sdp/syazdani/dataset-imagenet-ilsvrc2012-val/",
        "image_list": "/home/sdp/syazdani/dataset-imagenet-ilsvrc2012-val/val_map.txt",
        "total_sample_count": 50000
    },
    
    "enqueue-params": {
        "batch_size": 1
    }
}
